---
- name: Copy 'is_cluster_ready' file
  copy: dest=/bin/is_cluster_ready src=is_cluster_ready mode=0755

- set_fact: kube_pod_network_cidr='192.168.0.0/16'
  when: kube_network == 'calico'

- name: force handlers
  meta: flush_handlers

- name: Kubeadm init
  command: kubeadm init --pod-network-cidr={{kube_pod_network_cidr}} --token={{kube_token}} --token-ttl {{kube_token_ttl}} --apiserver-advertise-address={{kube_api_server}} creates=/etc/kubernetes/admin.conf

- name: wait Kube to start
  wait_for: port=6443

- include: kube_nets.yaml

- include: helm.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_install_helm | bool

- block:
    - copy: src=kubernetes-dashboard.yaml dest=/tmp/kubernetes-dashboard.yaml
    - command: kubectl apply -f /tmp/kubernetes-dashboard.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_deploy_dashboard | bool

- block:
    - copy: src=metrics-server.yaml dest=/tmp/metrics-server.yaml
    - command: kubectl apply -f /tmp/metrics-server.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_install_metrics | bool

- name: Add persistent volumes to kube cluster  
  block:
    - template: src=persistent-volumes.j2 dest=/tmp/kubernetes-persistent-volumes.yml
    - command: kubectl apply -f /tmp/kubernetes-persistent-volumes.yml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_persistent_volumes != []

- name: Install Git package
  package: name=git
  when: kube_apply_repos != []

- name: Download git repo "{{ item.repo }}"
  git:
    repo: "{{ item.repo }}"
    dest: "/tmp/{{ item.repo | basename }}"
    version: "{{ item.version }}"
  with_items: "{{ kube_apply_repos }}"

- name: apply path "{{ item.path }}"
  command: kubectl apply -f "{{ item.path }}" chdir="/tmp/{{ item.repo | basename }}"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  with_items: "{{ kube_apply_repos }}"

- name: Add Kube API server options
  lineinfile:
    dest: /etc/kubernetes/manifests/kube-apiserver.yaml
    line: '    - {{item.option}}={{item.value}}'
    regexp: '^    - {{item.option}}='
    insertafter: '    - kube-apiserver'
  notify: restart kubeapi
  with_items: "{{ kube_apiserver_options }}"

- copy:
    dest: /etc/profile.d/kube.sh
    content: "export KUBECONFIG=/etc/kubernetes/admin.conf"
  
- name: force handlers
  meta: flush_handlers

- block:
    - copy: src=ingress-nginx.yaml dest=/tmp/ingress-nginx.yaml
    - command: kubectl apply -f /tmp/ingress-nginx.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_install_ingress | bool

- block:
    - copy: src=nvidia-device-plugin.yml dest=/tmp/nvidia-device-plugin.yml
    - command: kubectl apply -f /tmp/nvidia-device-plugin.yml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_nvidia_support | bool

- block:
    - copy: src=kubernetes-dashboard-ingress.yaml dest=/tmp/kubernetes-dashboard-ingress.yaml
    - command: kubectl apply -f /tmp/kubernetes-dashboard-ingress.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_install_ingress | bool and kube_deploy_dashboard | bool

- include: kubeapps.yaml
  when: kube_install_kubeapps | bool

- include: nfs-client.yaml
  when: kube_install_nfs_client | bool
