---
- stat:
    path: /usr/bin/helm
  register: helm

# Install HELM
- block:
    - name: Copy helm install script
      copy: 
        src: helm.sh
        dest: /tmp/helm.sh
        mode: 0755

    - name: Execute helm install script
      command: bash /tmp/helm.sh -v {{kube_install_helm_version}}

  when: not helm.stat.exists
