---
  - name: Wait for tiller-deploy ready status
    command: kubectl rollout status deployment/tiller-deploy -n kube-system
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf

  - name: Add Bitnami Helm repo
    command: helm repo add bitnami https://charts.bitnami.com/bitnami

  - name: Check if kubeapps is installed
    command: helm status kubeapps
    register: helm_status
    ignore_errors: yes
    changed_when: false

  - name: Install kubeapps
    command: helm install --name kubeapps --namespace kubeapps bitnami/kubeapps --set 'mongodb.mongodbEnableIPv6=false'
    when: helm_status.rc != 0

  - copy: src=kubeapps-ingress.yaml dest=/tmp/kubeapps-ingress.yaml
  - command: kubectl apply -f /tmp/kubeapps-ingress.yaml
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
