---
- lineinfile:
    dest: /etc/sysctl.d/k8s.conf
    regexp: '^net.bridge.bridge-nf-call-iptables'
    line: 'net.bridge.bridge-nf-call-iptables = 1'
    create: yes
  notify: sysctl-system
  when: kube_network == 'flannel' or kube_network == 'kube-router'

- block:
    - template: src=flannel-net.j2 dest=/tmp/flannel-net.yml
    - command: kubectl apply -f /tmp/flannel-net.yml creates=/etc/cni/net.d/10-flannel.conflist
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_network == 'flannel'

- block:
    - copy: src=calico-net.yaml dest=/tmp/calico-net.yaml
    - command: kubectl apply -f /tmp/calico-net.yaml creates=/var/etcd/calico-data
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_network == 'calico'

- block:
    - copy: src=kuberouter-net.yaml dest=/tmp/kuberouter-net.yaml
    - command: kubectl apply -f /tmp/kuberouter-net.yaml creates=/etc/cni/net.d/10-kuberouter.conf
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_network == 'kube-router'

- block:
    - copy: src=weave-net.yaml dest=/tmp/weave-net.yaml
    - command: kubectl apply -f /tmp/weave-net.yaml creates=/etc/cni/net.d/10-weave.conf
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_network == 'weave'

