---
  - name: Wait for tiller-deploy ready status
    command: kubectl rollout status deployment/tiller-deploy -n kube-system
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf

  - name: Check if nfs-client is installed
    command: helm status nfs-client
    register: helm_status
    ignore_errors: yes
    changed_when: false

  - name: Install nfs-client-provisioner
    command: >
      helm install --name nfs-client stable/nfs-client-provisioner
      --set nfs.server=kubeserver.localdomain
      --set nfs.path=/pv 
      --set storageClass.defaultClass=true
      --set nodeSelector."node-role\.kubernetes\.io/master"=''
      --set tolerations[0].key=node-role.kubernetes.io/master
      --set tolerations[0].operator=Exists
      --set tolerations[0].effect=NoSchedule
    when: helm_status.rc != 0
