---
- name: Install Requisites
  yum: name=device-mapper-persistent-data,lvm2 state=installed

- block:

  - name: Download docker-ce.repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo

  - name: Install docker-ce 18.06.2
    yum: name=docker-ce-18.06.2.ce state=installed update_cache=yes

  when: docker_install | bool

- name: Create /etc/docker dir
  file: path=/etc/docker state=directory

- copy:
    dest: /etc/docker/daemon.json
    content: |
        {
          "storage-driver": "devicemapper"
        }
  register: devicemapper_storage

- name: Create /etc/systemd/system/docker.service.d dir
  file: path=/etc/systemd/system/docker.service.d state=directory recurse=yes

- name: Start docker service
  service: name=docker state=restarted enabled=yes
  when: devicemapper_storage is changed
